Feature/v2format
haruboring/smart-senkyo-extensions-web pull request #7
Opened 2022-12-11 12:15 UTC by gray-1to

## Description
本Pull Requestの目的は、V2フォーマットへの対応である。

v1フォーマットからv2フォーマットに以降するにあたり、列名や出力ファイルのページ構成が変更されたため対応した。

主な変更点は
・組織シート用列名、個人シート用列名への変更
・convertedデータの出力ファイルでの組織シート、個人シートへの対応
・tag1~50の受け取り、出力対応
である。

今回はAWS Lambda上で動く処理プログラム（[smart-senkyo-extensions](https://github.com/okoge-kaz/smart-senkyo-extensions)）での対応が未完了であるため、テスト用に作成したダミーレスポンスをAPIレスポンスの代わりとして用いている。
担当者(城戸さん)と話し合いののち、以下のような内容でレスポンスを行うとしている。
`
{
  "file_number": ファイル数,
  "**politician_data**": [
    {
      "file_name": ファイル名,
      "file_data": {
        "delete": {
          "0": "",
          "1": "delete",
          "2": "",
          "3": "deleteの日本語列名",
          "4": "",
          "5": "2nd",
        },
        "update": {
          "0": "",
          "1": "update",
          "2": "",
          "3": "updateの日本語列名",
          "4": "",
          "5": "2nd",
        },
       ...(以下略)
     }
   },
  ...(各ファイルごと続く)
  ],
  "**party_data**": [
    {
      "file_name": "test.csv",
      "file_data": {
        "delete": {
          "0": "",
          "1": "delete",
          "2": "",
          "3": "deleteの日本語列名",
          "4": "",
          "5": "2nd",
        },
        "update": {
          "0": "",
          "1": "update",
          "2": "",
          "3": "updateの日本語列名",
          "4": "",
          "5": "2nd",
        },
       ...(以下略)
     }
   },
  ...(各ファイルごと続く)
  ],
  "**invalid_data**": [
    {
      "file_name": "test.csv",
        "prize": {
            "0": "",
            "1": "prize",
            "2": "",
            "3": "称号",
            "4": "栄誉賞"
        },
       ...(以下略)
     }
   },
  ...(各ファイルごと続く)
  ]
}
`

## Related Issues

関連するIssueなし

## What users will see

開発者向け変更なのでなし

## What users will not see

開発者向け変更なのでなし

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Add Test Script

## How Has This Been Tested?

作成したダミーレスポンスにおけるテストをおこなった。

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

## For Reviewers

特になし

2022-12-12 02:22 UTC, okoge-kaz requested changes

2022-12-12 02:22 UTC, okoge-kaz commented on api/smart-senkyo-extensions/request.ts
> +	file_data: {}
ダミーデータの型をJSONにすることはできないのでしょうか？

2022-12-12 02:22 UTC, okoge-kaz commented on functions/getSmartSenkyoFormatBlobFromJson.tsx
> +        columnBasedPartyData.push(Object.values(partyFileData[columnName]))
mapやreduceを使ってpushやindexによる代入による配列の生成をやめるようにできませんか？

2022-12-12 02:36 UTC, okoge-kaz commented on api/smart-senkyo-extensions/request.ts
> +	file_data: {}
これは Must の修正ではありません。できればぐらいです

2022-12-12 02:37 UTC, okoge-kaz commented on functions/getSmartSenkyoFormatBlobFromJson.tsx
> +        columnBasedPartyData.push(Object.values(partyFileData[columnName]))
これも時間的余裕がない場合は、次のPull Requestにまわしていただいて大丈夫です

2022-12-12 04:53 UTC, haruboring commented on const/SmartSenkyoPartyColumnNames.tsx
> +export const SmartSenkyoPartyColumnNames: string[] = [
@gray-1to, @okoge-kaz 
伝達ミスでした。
本来は、組織(顧客の属している会社などの組織)のデータと、個人(顧客)のデータを出力するので
`Party`-> `Company`
`Politician`-> `Personal`
が適切でした。

2022-12-14 07:45 UTC, gray-1to commented on const/SmartSenkyoPartyColumnNames.tsx
> +export const SmartSenkyoPartyColumnNames: string[] = [
該当する名前を変更しました。
`Party`-> `Company`
`Politician`-> `Personal`

2022-12-14 07:46 UTC, gray-1to commented on const/SmartSenkyoPoliticianColumnNames.tsx
> +export const SmartSenkyoPoliticianColumnNames: string[] = [
該当する名前を変更しました。
`Party`-> `Company`
`Politician`-> `Personal`

2022-12-16 20:27 UTC, gray-1to commented on functions/getSmartSenkyoFormatBlobFromJson.tsx
> +        columnBasedPartyData.push(Object.values(partyFileData[columnName]))
array.push()を使用していたgetSmartSenkyoFormatBlobFromJson.ts, getBlobFromJson.ts, index.tsxにおいてarray.map()に修正しました。

2022-12-17 06:18 UTC, haruboring commented
@gray-1to 
求める出力形式は
`formatted_company_output.xlsx`,`formatted_company_output.xlsx`,`not_converted_info_output.xlsx`の3ファイルなのですがそうなっていますか？
コード読み慣れておらずレビューというレビューができていません。すいません。
最も重要な仕様変更は
3つのファイルが入力され、3つのファイルが出力されるようになったこと(今までは可変長)
なので質問させていただきました。

2023-02-20 07:42 UTC, haruboring approved these changes

2023-02-20 07:44 UTC, haruboring approved these changes

2023-02-20 07:46 UTC, merged